services:
  onboarder:
    build: .
    image: onboarder:latest
    environment:
      - spring.data.mongodb.uri=mongodb://user:password@localhost:27017/onboarder?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
  mongodb:
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
