services:
  onboarder:
    build: .
    image: onboarder:latest
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/onboarder?authSource=admin
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
